### ISSUE TITLE
Its asking for a local env

### ISSUE THREAD

**Issue by theCuriousHAT** [Heldenkombinat/Logodetect#38]
Traceback (most recent call last):
  File "C:\Users\AjayRawat\anaconda3\envs\logodetect\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AjayRawat\anaconda3\envs\logodetect\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AjayRawat\anaconda3\envs\logodetect\Scripts\logodetect.exe\__main__.py", line 4, in <module>
  File "C:\Users\AjayRawat\anaconda3\envs\logodetect\lib\site-packages\logodetect\__init__.py", line 8, in <module>
    os.path.join(os.environ["HOME"], ".hkt", "logodetect")
  File "C:\Users\AjayRawat\anaconda3\envs\logodetect\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by jorgedch** [comment]
As stated in the README file, this library is intended for Linux-based OS. Therefore, it can not be run on Windows.
